use crate::midi::setup_midi;
use midly::{live::LiveEvent, num::u7};
use std::fmt::Display;
use wasm_bindgen::prelude::*;

mod midi;
mod utils;

#[wasm_bindgen(start)]
pub async fn start() {
    let data = 0usize;
    setup_midi(parse_midi_message, data).await.unwrap();
}

fn parse_midi_message(timestamp: u64, message: &[u8], data: &mut usize) {
    let message = match LiveEvent::parse(message) {
        Ok(LiveEvent::Midi { channel, message }) => (channel, message),
        Err(e) => {
            jprintln!("Parsing midi message failed: {e:?}");
            return;
        }
        _ => return,
    };

    if let midly::MidiMessage::NoteOn { key, .. } = message.1 {
        jprintln!("{}", PianoKey::try_from(key).unwrap())
    }
}

enum PianoKey {
    A0,
    A0Sharp,
    B0,
    C1,
    C1Sharp,
    D1,
    D1Sharp,
    E1,
    F1,
    F1Sharp,
    G1,
    G1Sharp,
    A1,
    A1Sharp,
    B1,
    C2,
    C2Sharp,
    D2,
    D2Sharp,
    E2,
    F2,
    F2Sharp,
    G2,
    G2Sharp,
    A2,
    A2Sharp,
    B2,
    C3,
    C3Sharp,
    D3,
    D3Sharp,
    E3,
    F3,
    F3Sharp,
    G3,
    G3Sharp,
    A3,
    A3Sharp,
    B3,
    C4,
    C4Sharp,
    D4,
    D4Sharp,
    E4,
    F4,
    F4Sharp,
    G4,
    G4Sharp,
    A4,
    A4Sharp,
    B4,
    C5,
    C5Sharp,
    D5,
    D5Sharp,
    E5,
    F5,
    F5Sharp,
    G5,
    G5Sharp,
    A5,
    A5Sharp,
    B5,
    C6,
    C6Sharp,
    D6,
    D6Sharp,
    E6,
    F6,
    F6Sharp,
    G6,
    G6Sharp,
    A6,
    A6Sharp,
    B6,
    C7,
    C7Sharp,
    D7,
    D7Sharp,
    E7,
    F7,
    F7Sharp,
    G7,
    G7Sharp,
    A7,
    A7Sharp,
    B7,
    C8,
}

impl TryFrom<u7> for PianoKey {
    type Error = &'static str;

    fn try_from(value: u7) -> Result<Self, Self::Error> {
        let key = match value.as_int() {
            0..=20 | 109..=u8::MAX => return Err("invalid piano key"),
            21 => Self::A0,
            22 => Self::A0Sharp,
            23 => Self::B0,
            24 => Self::C1,
            25 => Self::C1Sharp,
            26 => Self::D1,
            27 => Self::D1Sharp,
            28 => Self::E1,
            29 => Self::F1,
            30 => Self::F1Sharp,
            31 => Self::G1,
            32 => Self::G1Sharp,
            33 => Self::A1,
            34 => Self::A1Sharp,
            35 => Self::B1,
            36 => Self::C2,
            37 => Self::C2Sharp,
            38 => Self::D2,
            39 => Self::D2Sharp,
            40 => Self::E2,
            41 => Self::F2,
            42 => Self::F2Sharp,
            43 => Self::G2,
            44 => Self::G2Sharp,
            45 => Self::A2,
            46 => Self::A2Sharp,
            47 => Self::B2,
            48 => Self::C3,
            49 => Self::C3Sharp,
            50 => Self::D3,
            51 => Self::D3Sharp,
            52 => Self::E3,
            53 => Self::F3,
            54 => Self::F3Sharp,
            55 => Self::G3,
            56 => Self::G3Sharp,
            57 => Self::A3,
            58 => Self::A3Sharp,
            59 => Self::B3,
            60 => Self::C4,
            61 => Self::C4Sharp,
            62 => Self::D4,
            63 => Self::D4Sharp,
            64 => Self::E4,
            65 => Self::F4,
            66 => Self::F4Sharp,
            67 => Self::G4,
            68 => Self::G4Sharp,
            69 => Self::A4,
            70 => Self::A4Sharp,
            71 => Self::B4,
            72 => Self::C5,
            73 => Self::C5Sharp,
            74 => Self::D5,
            75 => Self::D5Sharp,
            76 => Self::E5,
            77 => Self::F5,
            78 => Self::F5Sharp,
            79 => Self::G5,
            80 => Self::G5Sharp,
            81 => Self::A5,
            82 => Self::A5Sharp,
            83 => Self::B5,
            84 => Self::C6,
            85 => Self::C6Sharp,
            86 => Self::D6,
            87 => Self::D6Sharp,
            88 => Self::E6,
            89 => Self::F6,
            90 => Self::F6Sharp,
            91 => Self::G6,
            92 => Self::G6Sharp,
            93 => Self::A6,
            94 => Self::A6Sharp,
            95 => Self::B6,
            96 => Self::C7,
            97 => Self::C7Sharp,
            98 => Self::D7,
            99 => Self::D7Sharp,
            100 => Self::E7,
            101 => Self::F7,
            102 => Self::F7Sharp,
            103 => Self::G7,
            104 => Self::G7Sharp,
            105 => Self::A7,
            106 => Self::A7Sharp,
            107 => Self::B7,
            108 => Self::C8,
        };
        Ok(key)
    }
}

impl Display for PianoKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PianoKey::A0 => "A0",
            PianoKey::A0Sharp => "A0#",
            PianoKey::B0 => "B0",
            PianoKey::C1 => "C1",
            PianoKey::C1Sharp => "C1#",
            PianoKey::D1 => "D1",
            PianoKey::D1Sharp => "D1#",
            PianoKey::E1 => "E1",
            PianoKey::F1 => "F1",
            PianoKey::F1Sharp => "F1#",
            PianoKey::G1 => "G1",
            PianoKey::G1Sharp => "G1#",
            PianoKey::A1 => "A1",
            PianoKey::A1Sharp => "A1#",
            PianoKey::B1 => "B1",
            PianoKey::C2 => "C2",
            PianoKey::C2Sharp => "C2#",
            PianoKey::D2 => "D2",
            PianoKey::D2Sharp => "D2#",
            PianoKey::E2 => "E2",
            PianoKey::F2 => "F2",
            PianoKey::F2Sharp => "F2#",
            PianoKey::G2 => "G2",
            PianoKey::G2Sharp => "G2#",
            PianoKey::A2 => "A2",
            PianoKey::A2Sharp => "A2#",
            PianoKey::B2 => "B2",
            PianoKey::C3 => "C3",
            PianoKey::C3Sharp => "C3#",
            PianoKey::D3 => "D3",
            PianoKey::D3Sharp => "D3#",
            PianoKey::E3 => "E3",
            PianoKey::F3 => "F3",
            PianoKey::F3Sharp => "F3#",
            PianoKey::G3 => "G3",
            PianoKey::G3Sharp => "G3#",
            PianoKey::A3 => "A3",
            PianoKey::A3Sharp => "A3#",
            PianoKey::B3 => "B3",
            PianoKey::C4 => "C4",
            PianoKey::C4Sharp => "C4#",
            PianoKey::D4 => "D4",
            PianoKey::D4Sharp => "D4#",
            PianoKey::E4 => "E4",
            PianoKey::F4 => "F4",
            PianoKey::F4Sharp => "F4#",
            PianoKey::G4 => "G4",
            PianoKey::G4Sharp => "G4#",
            PianoKey::A4 => "A4",
            PianoKey::A4Sharp => "A4#",
            PianoKey::B4 => "B4",
            PianoKey::C5 => "C5",
            PianoKey::C5Sharp => "C5#",
            PianoKey::D5 => "D5",
            PianoKey::D5Sharp => "D5#",
            PianoKey::E5 => "E5",
            PianoKey::F5 => "F5",
            PianoKey::F5Sharp => "F5#",
            PianoKey::G5 => "G5",
            PianoKey::G5Sharp => "G5#",
            PianoKey::A5 => "A5",
            PianoKey::A5Sharp => "A5#",
            PianoKey::B5 => "B5",
            PianoKey::C6 => "C6",
            PianoKey::C6Sharp => "C6#",
            PianoKey::D6 => "D6",
            PianoKey::D6Sharp => "D6#",
            PianoKey::E6 => "E6",
            PianoKey::F6 => "F6",
            PianoKey::F6Sharp => "F6#",
            PianoKey::G6 => "G6",
            PianoKey::G6Sharp => "G6#",
            PianoKey::A6 => "A6",
            PianoKey::A6Sharp => "A6#",
            PianoKey::B6 => "B6",
            PianoKey::C7 => "C7",
            PianoKey::C7Sharp => "C7#",
            PianoKey::D7 => "D7",
            PianoKey::D7Sharp => "D7#",
            PianoKey::E7 => "E7",
            PianoKey::F7 => "F7",
            PianoKey::F7Sharp => "F7#",
            PianoKey::G7 => "G7",
            PianoKey::G7Sharp => "G7#",
            PianoKey::A7 => "A7",
            PianoKey::A7Sharp => "A7#",
            PianoKey::B7 => "B7",
            PianoKey::C8 => "C8",
        }
        .fmt(f)
    }
}
